#ifndef DEX_NAMEMAP_H_
#define DEX_NAMEMAP_H_

#include <unordered_map>
#include <vector>

#include "dex.h"

static std::vector<std::pair<int, const char*>> CLASS_ACCESS_FLAGS_NAMEVECTOR = {
  {CLASS_ACC_PUBLIC, "CLASS_ACC_PUBLIC"},
  {CLASS_ACC_PRIVATE, "CLASS_ACC_PRIVATE"},
  {CLASS_ACC_PROTECTED, "CLASS_ACC_PROTECTED"},
  {CLASS_ACC_STATIC, "CLASS_ACC_STATIC"},
  {CLASS_ACC_FINAL, "CLASS_ACC_FINAL"},
  {CLASS_ACC_INTERFACE, "CLASS_ACC_INTERFACE"},
  {CLASS_ACC_ABSTRACT, "CLASS_ACC_ABSTRACT"},
  {CLASS_ACC_SYNTHETIC, "CLASS_ACC_SYNTHETIC"},
  {CLASS_ACC_ANNOTATION, "CLASS_ACC_ANNOTATION"},
  {CLASS_ACC_ENUM, "CLASS_ACC_ENUM"},
};

static std::vector<std::pair<int, const char*>> FIELD_ACCESS_FLAGS_NAMEVECTOR = {
  {FIELD_ACC_PUBLIC, "FIELD_ACC_PUBLIC"},
  {FIELD_ACC_PRIVATE, "FIELD_ACC_PRIVATE"},
  {FIELD_ACC_PROTECTED, "FIELD_ACC_PROTECTED"},
  {FIELD_ACC_STATIC, "FIELD_ACC_STATIC"},
  {FIELD_ACC_FINAL, "FIELD_ACC_FINAL"},
  {FIELD_ACC_VOLATILE, "FIELD_ACC_VOLATILE"},
  {FIELD_ACC_TRANSIENT, "FIELD_ACC_TRANSIENT"},
  {FIELD_ACC_SYNTHETIC, "FIELD_ACC_SYNTHETIC"},
  {FIELD_ACC_ENUM, "FIELD_ACC_ENUM"},
};

static std::vector<std::pair<int, const char*>> METHOD_ACCESS_FLAGS_NAMEVECTOR = {
  {METHOD_ACC_PUBLIC, "METHOD_ACC_PUBLIC"},
  {METHOD_ACC_PRIVATE, "METHOD_ACC_PRIVATE"},
  {METHOD_ACC_PROTECTED, "METHOD_ACC_PROTECTED"},
  {METHOD_ACC_STATIC, "METHOD_ACC_STATIC"},
  {METHOD_ACC_FINAL, "METHOD_ACC_FINAL"},
  {METHOD_ACC_SYNCHRONIZED, "METHOD_ACC_SYNCHRONIZED"},
  {METHOD_ACC_BRIDGE, "METHOD_ACC_BRIDGE"},
  {METHOD_ACC_VARARGS, "METHOD_ACC_VARARGS"},
  {METHOD_ACC_NATIVE, "METHOD_ACC_NATIVE"},
  {METHOD_ACC_ABSTRACT, "METHOD_ACC_ABSTRACT"},
  {METHOD_ACC_STRICT, "METHOD_ACC_STRICT"},
  {METHOD_ACC_SYNTHETIC, "METHOD_ACC_SYNTHETIC"},
  {METHOD_ACC_CONSTRUCTOR, "METHOD_ACC_CONSTRUCTOR"},
  {METHOD_ACC_DECLARED_SYNCHRONIZED, "METHOD_ACC_DECLARED_SYNCHRONIZED"},
};

static std::unordered_map<int, const char*> ANNOTATION_VISIBILITY_NAMEMAP = {
  {VISIBILITY_BUILD, "VISIBILITY_BUILD"},
  {VISIBILITY_RUNTIME, "VISIBILITY_RUNTIME"},
  {VISIBILITY_SYSTEM, "VISIBILITY_SYSTEM"},
};

#endif  // DEX_NAMEMAP_H_
